# Generated by Django 4.2.2 on 2023-06-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='name')),
                ('description', models.CharField(verbose_name='description')),
                ('article', models.CharField(verbose_name='article')),
                ('weight', models.PositiveIntegerField(verbose_name='weight')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('material', models.CharField(verbose_name='material')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
